### PR TITLE
Added optional bottom toolbar and ability to disable scroll in list

### PR DESCRIPTION
**Pull request by ttorbik**
#### What has changed?
1. Added `enableMenuScroll` - This will allow you to disable the scroll inside the popup menu
2. Added `toolbarButtons` - this will allow you to show a toolbar at the bottom of the screen with a ToolbarButtonItem this can provide you with additional actions
3. Added `pull_request_template.md` - this will automatically populate future PR's with the template I am using now.
4. Updated `README.md` with additional gif and added my changes in the customization section.

#### Why is this change needed
Additional feature for certain use cases.

#### Screenshots & Videos

<table>
	<tr>
		<td>Bottom Toolbar</td>
	</tr>
	<tr>
		<td></td>
	</tr>
</table>

### CODE REVIEW

**Comment by henriquezanfa** [comment]
Hey @ttorbik  thanks for your PR
There are some conflicts with master, can you fix them?

**Comment by ttorbik** [comment]
hey @henriquezanfa I fixed the merge conflicts!

**Comment by ttorbik** [comment]
Hey @henriquezanfa any update on when this will be merged?

**Comment by henriquezanfa** [comment]
Hi @ttorbik thanks for making these changes and I'm sorry about the long time with no response.
I merged it with some adjustments. I changed the `toolbarButton` to `toolbarActions` and now I'm accepting any list of widgets there. It gives more flexibility for the devs to use it as they want.

**Pull request merged**
